/** Client-safe grej-meta (ingen fs). Hold synk med content/grej/*.mdx. */

export const GREJ_NAV = [
  { slug: "stoebjern-rene-skole", name: "Støbejerns-rene-skole" },
  { slug: "plancha-vs-stobejern", name: "Plancha vs. støbejern" },
  { slug: "airfryer-vs-ovn-opgoer", name: "Airfryer vs. ovn" },
  { slug: "airfryer-tilbehoer", name: "Airfryer-tilbehør" },
  { slug: "traekul-og-briketter-i-indkoebskurven", name: "Trækul og briketter" },
  { slug: "rygesmuld-flis-og-chunks", name: "Rygesmuld og chunks" },
  { slug: "rotisseri-til-grillen", name: "Rotisseri" },
  { slug: "hvilken-pizzaovn", name: "Hvilken pizzaovn" },
  { slug: "bagestaal-vs-bagesten", name: "Bagestål vs. sten" },
  { slug: "baalgrej-til-baghaven", name: "Bålgrej til baghaven" },
  { slug: "sous-vide-stave", name: "Sous vide-stave" },
  { slug: "trykkoger-vs-slowcooker", name: "Trykkoger vs. slowcooker" },
  { slug: "dehydrator-koebsguide", name: "Dehydrator" },
  { slug: "fermenteringsglas", name: "Fermenteringsglas" },
  { slug: "slibesten-vs-strygestaal", name: "Slibesten og stål" },
  { slug: "tradlost-stegetermometer", name: "Trådløst stegetermometer" },
  { slug: "vakuumpakkere", name: "Vakuumpakkere" },
  { slug: "koedhakkere", name: "Kødhakkere" },
  { slug: "gas-plancha-vs-kul-grill", name: "Gas-plancha vs. kul" },
  { slug: "stoebjernsgryde-storrelsesguide", name: "Dutch Oven-størrelse" },
  { slug: "gasregulatorer-slanger-sikkerhed", name: "Gasregulatorer" },
  { slug: "infrared-termometer-pizza", name: "IR-termometer" },
  { slug: "pizzaspader", name: "Pizzaspader" },
  { slug: "mikroboelgeovnen", name: "Mikrobølgeovnen" },
  { slug: "mandolinjern", name: "Mandolinjern" },
  { slug: "koldroegningsbakke", name: "Koldrøgningsbakke" },
  { slug: "smedejern-vs-stobejern-baalpande", name: "Smedejern vs. støbejern" },
  { slug: "skaerebraet-endetrae-vs-plastik", name: "Skærebræt" },
  { slug: "elektriske-knivslibere", name: "Knivslibere" },
  { slug: "ismaskine-kompressor-vs-fryseelement", name: "Ismaskine" },
  { slug: "sukkertermometer", name: "Sukkertermometer" },
  { slug: "stavblender", name: "Stavblender" },
  { slug: "chiffonflaske-sifon", name: "Sifonflaske" },
  { slug: "belaegning-teflon-keramik-staal", name: "Pande-belægning" },
  { slug: "kobbergryder", name: "Kobbergryder" },
] as const;

export type GrejNavSlug = (typeof GREJ_NAV)[number]["slug"];
