/** Client-safe guide-meta (ingen fs). Hold synk med content/guides/*.mdx. */

export const GUIDE_NAV = [
  { slug: "airfryer-for-begyndere", name: "Airfryer for begyndere" },
  { slug: "kernetemperatur", name: "Kernetemperatur" },
  { slug: "culottesteg", name: "Culottesteg" },
  { slug: "hjemmelavet-pizza", name: "Hjemmelavet pizza" },
  { slug: "pulled-pork", name: "Pulled pork" },
  { slug: "fermentering-for-begyndere", name: "Fermentering" },
  { slug: "sunde-teknikker", name: "Sunde teknikker" },
  { slug: "smags-hacks-syre-salt-krydderier", name: "Smags-hacks" },
  { slug: "magre-proteinkilder-grill-airfryer", name: "Protein-omregner" },
  { slug: "groentsager-med-guldskorpe", name: "Grøntsager med guldskorpe" },
  { slug: "syltning", name: "Syltning" },
  { slug: "roegning-hjemme", name: "Røgning hjemme" },
  { slug: "grydebroed-og-focaccia", name: "Grydebrød og focaccia" },
  { slug: "smash-burger", name: "Smash burger" },
  { slug: "saltguide", name: "Saltguide" },
  { slug: "dehydrering-for-noerder", name: "Dehydrering" },
  { slug: "sous-vide-grill", name: "Sous vide + sear" },
  { slug: "baalmad", name: "Bålmad" },
  { slug: "stegeoverflader", name: "Stegeoverflader" },
  { slug: "trykkoger-og-slowcooker", name: "Trykkoger" },
  { slug: "avanceret-fermentering", name: "Koji og miso" },
  { slug: "saucer-fond-reduktion", name: "Fond og saucer" },
  { slug: "konfittering", name: "Konfittering" },
  { slug: "grill-for-begyndere", name: "Grill for begyndere" },
  { slug: "grillrist-og-pander-pleje", name: "Grillrist og pander" },
  { slug: "meal-prep", name: "Meal prep" },
  { slug: "mad-paa-budget", name: "Mad på budget" },
  { slug: "frysning-og-optoening", name: "Frysning og optøning" },
  { slug: "groentsager-paa-grillen", name: "Grøntsager på grillen" },
  { slug: "boerenevenlig-madlavning", name: "Børnevenlig madlavning" },
  { slug: "fryseguide-madpakke", name: "Fryseguide til madpakke" },
  { slug: "skjul-groentsager-kraesne-boern", name: "Skjul grøntsager" },
  { slug: "airfryer-boernemad-15-minutter", name: "Airfryer-børnemad" },
  { slug: "proteiner-uden-koed-boern", name: "Protein uden kød" },
  { slug: "fingermad-snacks-til-turen", name: "Fingermad til turen" },
  { slug: "bloed-mad-taender-boejle", name: "Blød mad til gummer" },
  { slug: "boerenefoedselsdag-paa-budget", name: "Børnefødselsdag på budget" },
  { slug: "sund-fredagsslik", name: "Sund fredagsslik" },
  { slug: "foerste-rigtige-mad-baby", name: "Fra mos til familiens mad" },
  { slug: "byg-selv-retter-middagsbordet", name: "Byg-selv-retter" },
  { slug: "marinader-og-rubs", name: "Marinader og rubs" },
  { slug: "bageskole-gaer-og-haevning", name: "Bageskole" },
  { slug: "sikker-madlavning", name: "Sikker madlavning" },
  { slug: "optoening-af-koed", name: "Optøning af kød" },
  { slug: "tilberedning-fra-frost", name: "Fra frost" },
  { slug: "flaeskesteg-i-airfryer", name: "Flæskesteg i airfryer" },
  { slug: "pizzadej-fejlfinding", name: "Pizzadej fejlfinding" },
  { slug: "holdbarhed-i-koeleskab", name: "Holdbarhed i køleskab" },
  { slug: "genopvarmning-af-mad", name: "Genopvarmning" },
  { slug: "koed-svind-og-portioner", name: "Kød svind og portioner" },
  { slug: "roget-smag-uden-rygeovn", name: "Røgsmag uden ryger" },
  { slug: "rensning-af-svampe", name: "Rensning af svampe" },
  { slug: "traekul-vs-briketter", name: "Trækul vs. briketter" },
  { slug: "kan-man-fryse", name: "Kan man fryse …?" },
  { slug: "ris-fejlfinding", name: "Ris der klistrer" },
  { slug: "red-maden", name: "Red maden" },
  { slug: "natron-og-bagepulver", name: "Natron og bagepulver" },
  { slug: "stoebjern-seasoning", name: "Støbejern seasoning" },
  { slug: "hakket-oksekoed-farve", name: "Hakket oksekød farve" },
  { slug: "omregning-gram-ske-dl", name: "Gram, skeer og dl" },
  { slug: "airfryer-ovn-omregning", name: "Airfryer vs. ovn" },
  { slug: "stegning-olier-roegpunkt", name: "Olie og røgpunkt" },
  { slug: "sproede-pomfritter", name: "Sprøde pomfritter" },
  { slug: "andesteg-komplet-guide", name: "Andesteg komplet" },
  { slug: "mortensaften-tilbehoer", name: "Mortensaften-tilbehør" },
  { slug: "julemenu-sammensaetning", name: "Julemenu" },
  { slug: "danske-klassikere-guide", name: "Danske klassikere" },
] as const;

export type GuideNavSlug = (typeof GUIDE_NAV)[number]["slug"];

export const GUIDE_LINKS: {
  slug: GuideNavSlug;
  title: string;
  description: string;
  recipes: string[];
}[] = [
  {
    slug: "airfryer-for-begyndere",
    title: "Airfryer for begyndere — sprød mad uden gætteri",
    description:
      "Komplet guide til airfryer: temperatur, tid, forvarmning, olie og de fejl der gør maden blød.",
    recipes: [
      "airfryer/pommes-frites-bagekartofler",
      "airfryer/frosne-pomfritter",
      "airfryer/crispy-chicken-tenders",
      "airfryer/hjemmelavede-kyllingenuggets",
      "airfryer/flaeskesvaer-sennepsstoev",
      "airfryer/bacon",
      "airfryer/hel-kylling",
      "airfryer/fiskefileter-panko",
      "airfryer/smashed-potato-salad",
      "airfryer/haardkogte-aeg-meal-prep",
      "airfryer/frosne-rundstykker",
      "airfryer/spidskaal",
      "airfryer/chili-lime-kyllingenuggets",
    ],
  },
  {
    slug: "kernetemperatur",
    title: "Kernetemperatur — komplet tabel til grill, pande, ovn og sous vide",
    description:
      "Kernetemperatur for okse, svin, lam, kylling og fisk. Træk-temperatur, carryover og probe-placering.",
    recipes: [
      "grill/kernetemperatur-grill",
      "grill/tomahawk-steak",
      "grill/culottesteg-paa-grill",
      "grill/oksemoerbrad-paa-grill",
      "sous-vide/ribeye-sous-vide",
      "sous-vide/culottesteg-sous-vide",
      "sous-vide/hel-kylling-sous-vide",
      "grill/hel-kylling-gasgrill-tid",
      "grill/pulled-pork",
      "roeg/smoked-pulled-pork",
      "sous-vide/pulled-pork-sous-vide",
      "sous-vide/laksefilet-sous-vide",
      "grill/grillet-lakseside-citron",
    ],
  },
  {
    slug: "culottesteg",
    title: "Culottesteg — fra rå til rosa på grill, ovn, airfryer og sous vide",
    description:
      "Culottesteg komplet: udskæring, fedtkappe, kernetemperatur, reverse sear og hvile.",
    recipes: [
      "grill/culottesteg-paa-grill",
      "grill/culottesteg-rotisseri",
      "grill/grillet-kalveculotte-urtemarinade",
      "sous-vide/culottesteg-sous-vide",
      "airfryer/rosa-culottesteg",
      "grill/klassisk-kartoffelsalat",
      "grill/kartoffelsalat-radiser",
      "dips/chimichurri",
      "dips/mormordressing",
      "grill/groentsager-paa-grill",
    ],
  },
  {
    slug: "hjemmelavet-pizza",
    title: "Hjemmelavet pizza — dej, varme og ovn",
    description:
      "Pizzadej, koldhæv, neapolitansk varme og fejl som våd midte.",
    recipes: [
      "roeremaskine/neapolitansk-pizzadej-roeremaskine",
      "roeremaskine/koldhaevet-pizzadej-roeremaskine",
      "roeremaskine/hurtig-pizzadej-roeremaskine",
      "grill/pizzadej-grill",
      "pizzaovn/neapolitansk-pizza-pizzaovn",
      "pizzaovn/pizza-margherita-pizzaovn",
      "pizzaovn/detroit-style-pizza-pizzaovn",
      "pizzaovn/calzone-skinke-ricotta-pizzaovn",
      "pizzaovn/panuozzo-pizza-sandwich-pizzaovn",
      "pizzaovn/focaccia-rosmarin-cherrytomater-pizzaovn",
      "grill/grillet-focaccia-pizzasten",
      "stobejern/overnight-sourdough-cast-iron-pizza",
      "roeremaskine/detroit-pizzadej-roeremaskine",
    ],
  },
  {
    slug: "pulled-pork",
    title: "Pulled pork — nakkefilet til trækbar",
    description:
      "Pulled pork komplet: nakkefilet, rub, stall, probe tender og 93–95 °C.",
    recipes: [
      "grill/pulled-pork",
      "grill/asiatisk-sticky-pulled-pork",
      "roeg/smoked-pulled-pork",
      "stobejern/pulled-pork-dutch-oven",
      "sous-vide/pulled-pork-sous-vide",
      "trykkoger/pulled-pork-trykkoger",
      "roeg/smoked-pork-belly-sliders",
      "dips/bbq-sauce",
      "grill/klassisk-kartoffelsalat",
      "sylte/syltede-roedloeg-10-minutter",
      "roeremaskine/brioche-burgerboller-roeremaskine",
    ],
  },
  {
    slug: "fermentering-for-begyndere",
    title: "Fermentering for begyndere — salt, lage og mælkesyre",
    description:
      "Fermentering hjemme: 2 % salt, lage, kahm versus skimmel og temperatur.",
    recipes: [
      "fermentering/klassisk-sauerkraut",
      "fermentering/autentisk-koreansk-kimchi",
      "fermentering/maelkesyregaerde-agurker",
      "fermentering/fermenterede-roedloeg",
      "fermentering/nordisk-gravad-laks",
      "fermentering/saltkonserverede-citroner",
      "fermentering/fermenteret-chili-hot-sauce",
      "fermentering/hjemmelavet-bacon-saltning",
      "fermentering/fermenterede-guleroedsstave-ingefaer",
      "fermentering/curtido",
    ],
  },
  {
    slug: "sunde-teknikker",
    title: "Sunde teknikker — maksimal smag og mæthed",
    description:
      "Protein, Maillard og fermentering. Maksimal smag og mæthed med færre tomme kalorier.",
    recipes: [
      "ovn/protein-pizzasnegle-hytteost-fuldkorn",
      "airfryer/chili-lime-kyllingenuggets",
      "grill/flanksteak-roedbede-kaal-salat",
      "pande/shakshuka-hytteost-creme",
      "grill/kimchi-marineret-lakseside",
      "pande/salte-hytteostvafler",
      "ovn/viral-hytteost-fladbroed",
      "airfryer/hjemmelavede-kyllingenuggets",
      "airfryer/spidskaal",
      "fermentering/klassisk-sauerkraut",
      "fermentering/autentisk-koreansk-kimchi",
      "pande/shakshuka",
    ],
  },
  {
    slug: "smags-hacks-syre-salt-krydderier",
    title: "Smags-hacks: syre, salt og krydderier i stedet for mere fedt",
    description:
      "Syre, salt, chili og røg så maden smager færdig uden at drukne i fløde.",
    recipes: [
      "dips/chimichurri",
      "grill/flanksteak-roedbede-kaal-salat",
      "grill/kimchi-marineret-lakseside",
      "pande/shakshuka-hytteost-creme",
      "fermentering/autentisk-koreansk-kimchi",
      "fermentering/klassisk-sauerkraut",
      "dips/mormordressing",
    ],
  },
  {
    slug: "magre-proteinkilder-grill-airfryer",
    title: "Protein-omregner: magre kilder til grill og airfryer",
    description:
      "Tabel med protein, grill og airfryer-teknik til kylling, flank, laks, hytteost og tofu.",
    recipes: [
      "airfryer/chili-lime-kyllingenuggets",
      "grill/flanksteak-roedbede-kaal-salat",
      "grill/kimchi-marineret-lakseside",
      "pande/shakshuka-hytteost-creme",
      "ovn/protein-pizzasnegle-hytteost-fuldkorn",
      "airfryer/hjemmelavede-kyllingenuggets",
      "airfryer/sproed-tofu-soya-sesam",
      "airfryer/kikaerter",
      "airfryer/haardkogte-aeg-meal-prep",
      "pande/salte-hytteostvafler",
    ],
  },
  {
    slug: "groentsager-med-guldskorpe",
    title: "Grøntsager med guldskorpe — hård varme, tør overflade",
    description:
      "Maillard på kål, rødbede og spidskål. Hård varme, tør overflade, salt og syre.",
    recipes: [
      "airfryer/spidskaal",
      "grill/flanksteak-roedbede-kaal-salat",
      "grill/groentsager-paa-grill",
      "airfryer/blomkaals-bites",
      "pande/hakket-oksekoed-spidskaal",
    ],
  },
  {
    slug: "syltning",
    title: "Syltning — lage, forhold og glas der holder",
    description:
      "Syltning med eddike: forhold, hurtigsylt versus kogning, agurker, rødløg og asier.",
    recipes: [
      "sylte/syltede-agurker",
      "sylte/hurtigsyltede-agurker-10-minutter",
      "sylte/gammeldags-agurkesalat-peberkorn",
      "sylte/asier",
      "sylte/syltede-roedloeg",
      "sylte/syltede-roedloeg-10-minutter",
      "sylte/syltede-jalapenos",
      "sylte/cowboy-candy",
      "sylte/syltede-roedbeder",
      "sylte/syltede-radiser",
      "sylte/klassisk-roedkaal-andefedt",
      "sylte/piccalilli-chow-chow",
      "sylte/pickled-onion-rings",
      "sylte/watermelon-rind-pickles",
      "sylte/klassiske-kryddersild",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "roegning-hjemme",
    title: "Røgning hjemme — koldrøg versus varmrøg, den komplette guide",
    description:
      "Koldrøg vs. varmrøg, træsorter, røg-generatorer, pellicle og sikkerhed.",
    recipes: [
      "roeg/koldroget-laks",
      "grill/koldroget-laks-paa-grill",
      "roeg/hjemmelavet-koldroget-bacon",
      "roeg/varmroget-lakseside",
      "roeg/varmroget-sild",
      "roeg/smoked-beef-brisket",
      "roeg/smoked-pork-ribs",
      "roeg/smoked-pulled-pork",
      "roeg/roget-salt",
      "roeg/smoked-cream-cheese",
      "fermentering/hjemmelavet-bacon-saltning",
    ],
  },
  {
    slug: "grydebroed-og-focaccia",
    title: "Grydebrød og focaccia — skorpe i støbejern",
    description:
      "Grydebrød og focaccia: hydrering, salt i dejen, damp under låg, surdej versus gær.",
    recipes: [
      "stobejern/klassisk-grydebroed",
      "stobejern/grydebroed-oel-kerner",
      "stobejern/grydebroed-hytteost",
      "stobejern/rugbroeds-grydebroed",
      "stobejern/hvidloegs-krydderurte-focaccia",
      "roeremaskine/focaccia-havsalt-roeremaskine",
      "roeremaskine/grydebroad-roeremaskine",
      "pizzaovn/focaccia-rosmarin-cherrytomater-pizzaovn",
      "pizzaovn/roedbede-focaccia-timian-pizzaovn",
      "grill/grillet-focaccia-pizzasten",
      "roeremaskine/ciabatta-roeremaskine",
      "roeremaskine/naanbroed-roeremaskine",
    ],
  },
  {
    slug: "smash-burger",
    title: "Smash burger — plancha, grill og sauce",
    description:
      "Smash burger hjemme: fedtprocent, smash-teknik, ost, bolle og pickles.",
    recipes: [
      "plancha/smash-burger-paa-plancha",
      "plancha/smash-burger-sliders-paa-plancha",
      "stobejern/smash-burgers-stobejern",
      "pizzaovn/smash-burgers-pizzaovn",
      "grill/hjemmelavet-burger",
      "roeremaskine/brioche-burgerboller-roeremaskine",
      "dips/burgersauce",
      "dips/aioli",
      "sylte/syltede-roedloeg-10-minutter",
      "sylte/hurtigsyltede-agurker-10-minutter",
      "airfryer/frosne-pomfritter",
      "airfryer/bacon",
    ],
  },
  {
    slug: "saltguide",
    title: "Den ultimative saltguide — typer, procenter og funktion",
    description:
      "Flagesalt, dæmningssalt, nitritsalt og koldrøget salt. Tørsaltning versus saltlage.",
    recipes: [
      "fermentering/gourmetsaltning-oksekoed",
      "fermentering/hjemmelavet-bacon-saltning",
      "fermentering/klassisk-sauerkraut",
      "fermentering/spraengt-svinemoerbrad",
      "fermentering/saltede-aeggeblommer",
      "fermentering/saltede-kapers",
      "fermentering/nordisk-gravad-laks",
      "roeg/roget-salt",
      "dehydrator/urtesalt-dehydrator",
      "dehydrator/ramslogssalt-dehydrator",
      "ovn/braendt-hvidloegssalt",
    ],
  },
  {
    slug: "dehydrering-for-noerder",
    title: "Dehydrering for nørder — jerky, støv og umami-bomber",
    description:
      "Temperaturer og tider til jerky, svampestøv, urtesalt og kapers.",
    recipes: [
      "dehydrator/beef-jerky-dehydrator",
      "dehydrator/bacon-jerky-dehydrator",
      "dehydrator/salmon-jerky-dehydrator",
      "dehydrator/toerrede-svampe-dehydrator",
      "dehydrator/svampesalt-dehydrator",
      "dehydrator/tomatpulver-dehydrator",
      "dehydrator/loegpulver-dehydrator",
      "dehydrator/urtesalt-dehydrator",
      "dehydrator/semidried-tomater-dehydrator",
      "fermentering/saltede-kapers",
      "dehydrator/flaeskesvaer-dehydrator",
    ],
  },
  {
    slug: "sous-vide-grill",
    title: "Sous vide + grill og pande — reverse sear der rammer",
    description:
      "Tider og temperaturer til bad, genopvarmning og skorpe på plancha og støbejern.",
    recipes: [
      "sous-vide/ribeye-sous-vide",
      "sous-vide/entrecote-sous-vide",
      "sous-vide/tomahawk-steak-sous-vide",
      "sous-vide/culottesteg-sous-vide",
      "sous-vide/flanksteak-sous-vide",
      "sous-vide/laksefilet-sous-vide",
      "sous-vide/pulled-pork-sous-vide",
      "plancha/tomahawk-steak-board-sauce-plancha",
      "stobejern/cast-iron-ribeye",
      "fermentering/gourmetsaltning-oksekoed",
    ],
  },
  {
    slug: "baalmad",
    title: "Bålmad — glødebed, trefod og Dutch Oven i ilden",
    description:
      "Styring af varme med brænde, glødebed, trefod og Dutch Oven i gløderne.",
    recipes: [
      "baalmad/ribeye-med-urtesmoer",
      "baalmad/tomahawk-steak-paa-aaben-ild",
      "baalmad/gullasch-i-dutch-oven",
      "baalmad/ossobuco-i-gloedene",
      "baalmad/gloedestegte-porrer",
      "baalmad/skipperlabskovs-over-baal",
      "baalmad/hvidloegs-focaccia-i-gryde",
      "baalmad/stobejerns-focaccia-med-rosmarin",
      "baalmad/plankelaks-med-enebaer",
      "baalmad/flanksteak-med-chimichurri",
    ],
  },
  {
    slug: "stegeoverflader",
    title: "Stegeoverflader — støbejern, plancha og rustfrit stål",
    description:
      "Hvornår du bruger hvad, seasoning af støbejern og Maillard uden at brænde på.",
    recipes: [
      "stobejern/cast-iron-ribeye",
      "stobejern/smash-burgers-stobejern",
      "plancha/smash-burger-paa-plancha",
      "plancha/tomahawk-steak-board-sauce-plancha",
      "plancha/engelsk-bof-paa-plancha",
      "stobejern/klassisk-grydebroed",
      "stobejern/stegte-flaeskesider",
      "pande/pandeskaft",
      "sous-vide/ribeye-sous-vide",
    ],
  },
  {
    slug: "trykkoger-og-slowcooker",
    title: "Trykkoger og slowcooker — kollagen, tid og væske",
    description:
      "Hvordan tryk nedbryder kollagen i skanker og oksehaler. Tid og væskeforhold.",
    recipes: [
      "trykkoger/osso-buco-trykkoger",
      "trykkoger/svinekaeber-trykkoger",
      "trykkoger/pulled-pork-trykkoger",
      "trykkoger/fond-trykkoger",
      "trykkoger/oksespidsbryst-trykkoger",
      "trykkoger/gullasch-trykkoger",
      "stobejern/okseskank-roedvin",
      "stobejern/oksehale-moerkt-oel",
      "stobejern/pulled-pork-dutch-oven",
      "sous-vide/osso-buco-sous-vide",
    ],
  },
  {
    slug: "avanceret-fermentering",
    title: "Avanceret fermentering — koji, miso og eddiker fra bunden",
    description:
      "Aspergillus oryzae, shio koji, miso, garum og frugteddiker.",
    recipes: [
      "fermentering/klassisk-shio-koji",
      "fermentering/hjemmelavet-shiro-miso",
      "fermentering/koji-modnet-steak",
      "fermentering/gochujang-fra-bunden",
      "fermentering/hjemmelavet-shoyu-svampe",
      "fermentering/lyn-garum-oksekoed",
      "fermentering/klassisk-romersk-fiskegarum",
      "fermentering/fermenteret-aebleeddike",
      "fermentering/hjemmelavet-eddike-vinrester",
      "fermentering/kombucha-eddike",
    ],
  },
  {
    slug: "saucer-fond-reduktion",
    title: "Saucer på fond og reduktion — gastrique, montering og glace",
    description:
      "Reduktion, gastrique, koldt smør og glinsende glace.",
    recipes: [
      "trykkoger/fond-trykkoger",
      "ovn/bagt-marvben-persillesalat",
      "dips/whiskeysauce",
      "dips/bbq-sauce",
      "dips/hovmestersauce",
      "stobejern/okseskank-roedvin",
      "stobejern/oksehale-moerkt-oel",
      "stobejern/ossobuco-alla-milanese",
      "plancha/tomahawk-steak-board-sauce-plancha",
      "pande/torskefilet-smoersauce",
    ],
  },
  {
    slug: "konfittering",
    title: "Konfittering — mørhed og hold i rent fedt",
    description:
      "Temperaturstyring omkring 85–90 °C i andefedt, svinefedt eller olivenolie.",
    recipes: [
      "stobejern/confiterede-andelaar",
      "sous-vide/andelaar-sous-vide",
      "stobejern/confiterede-hvidloeg-andefedt",
      "sous-vide/hvidloegsconfit-sous-vide",
      "sylte/hvidloegsconfit",
      "ovn/langtidsbagte-confiterede-cherrytomater",
      "fermentering/saltet-toerret-andebryst",
      "sous-vide/hel-and-sous-vide",
    ],
  },
  {
    slug: "grill-for-begyndere",
    title: "Den store grill-guide til begyndere — gas vs. kul",
    description:
      "Gas versus kul, tænding, zoner, direkte og indirekte varme.",
    recipes: [
      "grill/hel-kylling-gasgrill-tid",
      "grill/grillkylling",
      "grill/kernetemperatur-grill",
      "grill/tomahawk-steak",
      "grill/culottesteg-paa-grill",
      "grill/svinemoerbrad",
      "grill/groentsager-paa-grill",
      "grill/majskolber",
      "grill/pulled-pork",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "grillrist-og-pander-pleje",
    title: "Klargøring og pleje af grillriste og pander",
    description:
      "Afbrænding, rust, seasoning og kød der ikke hænger i.",
    recipes: [
      "stobejern/cast-iron-ribeye",
      "stobejern/smash-burgers-stobejern",
      "stobejern/stegte-flaeskesider",
      "plancha/smash-burger-paa-plancha",
      "pande/pandeskaft",
      "grill/culottesteg-paa-grill",
      "grill/tomahawk-steak",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "meal-prep",
    title: "Måltidsforberedelse (meal prep) til en travl uge",
    description:
      "Planlæg, kog, pak og opbevar så hverdagen er 10 minutter.",
    recipes: [
      "airfryer/haardkogte-aeg-meal-prep",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "gryde/kylling-i-karry",
      "gryde/one-pot-pasta",
      "pande/hakket-oksekoed-spidskaal",
      "pande/frittata",
      "grill/pulled-pork",
      "dips/hummus",
      "ovn/grove-proteinboller-kerner-hytteost",
      "ovn/protein-pizzasnegle-hytteost-fuldkorn",
    ],
  },
  {
    slug: "mad-paa-budget",
    title: "Den nemme guide til mad på budget",
    description:
      "Madspild, sæson, billige udskæringer og gryder der mætter.",
    recipes: [
      "gryde/skipperlabskovs",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "gryde/millionboef",
      "gryde/hvidkaalssuppe-flaesk",
      "gryde/boller-i-karry",
      "pande/biksemad-spejlaeg",
      "pande/hakkeboef-loeg-spejlaeg",
      "pande/stegt-lever-bloede-loeg",
      "gryde/one-pot-poelseret",
    ],
  },
  {
    slug: "frysning-og-optoening",
    title: "Alt om frysning og optøning af mad",
    description:
      "Hvad der tåler frost, sikker tø af kød og holdbarhed ved −18 °C.",
    recipes: [
      "grill/pulled-pork",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "gryde/gullasch",
      "stobejern/klassisk-grydebroed",
      "roeremaskine/brioche-burgerboller-roeremaskine",
      "airfryer/frosne-pomfritter",
      "airfryer/frosne-rundstykker",
      "pande/gyoza-fra-frost-pande",
    ],
  },
  {
    slug: "groentsager-paa-grillen",
    title: "Grøntsager på grillen — tider og teknikker",
    description:
      "Majs, asparges, peber og spidskål uden sort skorpe og slatten midte.",
    recipes: [
      "grill/groentsager-paa-grill",
      "grill/majskolber",
      "grill/elote-majskolber",
      "grill/groenne-asparges",
      "grill/grillet-spidskaal",
      "grill/grillet-aubergine",
      "grill/grillet-squash",
      "grill/grillede-tomater",
      "grill/groentsagsspyd",
      "grill/grillede-portobellosvampe-hvidloegssmoer",
    ],
  },
  {
    slug: "boerenevenlig-madlavning",
    title: "Børnevenlig madlavning — succes med ungerne",
    description:
      "Opgaver efter alder, mindre kaos, retter der tåler små hænder.",
    recipes: [
      "pande/amerikanske-pandekager",
      "pande/frikadeller-pande",
      "gryde/boller-i-karry",
      "grill/hjemmelavet-burger",
      "gryde/one-pot-pasta",
      "pande/tacos-krydret-hakkekoed",
      "roeremaskine/pizzasnegle-roeremaskine",
      "ovn/koldhaevede-morgenboller-oelandshvede",
      "airfryer/hjemmelavede-kyllingenuggets",
      "pande/franske-toast",
    ],
  },
  {
    slug: "marinader-og-rubs",
    title: "Hjemmelavede marinader og rubs — de 5 grundsmage",
    description:
      "Olie, syre og krydderi til kylling, svin og okse. Rub til bark.",
    recipes: [
      "dips/graesk-yoghurtmarinade",
      "dips/asiatisk-marinade-soya-ingefaer",
      "dips/nordisk-grillmarinade",
      "dips/bbq-dry-rub",
      "dips/hvidloegsmarinade-grill",
      "dips/roed-grillmarinade-koteletter",
      "dips/whisky-marinade-oksekoed",
      "dips/citron-urte-marinade-fisk",
      "dips/kaffe-rub",
      "dips/ingefaer-sesam-marinade-tofu",
      "dips/chimichurri",
      "dips/sennep-honning-marinade-dressing",
      "dips/bbq-sauce",
      "grill/pulled-pork",
    ],
  },
  {
    slug: "bageskole-gaer-og-haevning",
    title: "Den nemme bageskole — gær, hævning og temperatur",
    description:
      "Hvorfor dejen ikke hæver, lunt versus koldt vand, boller der ikke er tætte.",
    recipes: [
      "stobejern/klassisk-grydebroed",
      "ovn/koldhaevede-morgenboller-oelandshvede",
      "roeremaskine/brioche-burgerboller-roeremaskine",
      "roeremaskine/focaccia-havsalt-roeremaskine",
      "roeremaskine/grydebroad-roeremaskine",
      "roeremaskine/hurtig-pizzadej-roeremaskine",
      "roeremaskine/koldhaevet-pizzadej-roeremaskine",
      "airfryer/frosne-rundstykker",
    ],
  },
  {
    slug: "sikker-madlavning",
    title: "Sikker madlavning — hygiejne, bakterier og holdbarhed",
    description:
      "To-timers-regel, kylling 74 °C, krydskontaminering og rester.",
    recipes: [
      "grill/hel-kylling-gasgrill-tid",
      "grill/kernetemperatur-grill",
      "airfryer/hel-kylling",
      "pande/kyllingebryst-pande",
      "pande/frikadeller-pande",
      "gryde/bolognese",
      "airfryer/haardkogte-aeg-meal-prep",
    ],
  },
  {
    slug: "optoening-af-koed",
    title: "Den store optønings-guide: Sådan tør du kød hurtigt (og sikkert) op",
    description:
      "Koldt vand, mikroovn og køleskab — tider efter tykkelse, og hvorfor varmt vand er forbudt.",
    recipes: [
      "pande/gyoza-fra-frost-pande",
      "airfryer/frosne-pomfritter",
      "airfryer/frosne-rundstykker",
      "grill/pulled-pork",
      "pande/kyllingebryst-pande",
      "gryde/bolognese",
    ],
  },
  {
    slug: "tilberedning-fra-frost",
    title: "Kernetemperatur på frosset kød — kan man tilberede direkte fra frost?",
    description:
      "Frossen kyllingefilet, steak og hakket i airfryer, sous vide og pande. Tider og risici.",
    recipes: [
      "sous-vide/ribeye-sous-vide",
      "airfryer/koteletter",
      "pande/kyllingebryst-pande",
      "airfryer/hel-kylling",
      "grill/tomahawk-steak",
      "pande/gyoza-fra-frost-pande",
    ],
  },
  {
    slug: "flaeskesteg-i-airfryer",
    title: "Flæskesteg i airfryer: genvej til sprøde svær uden gætteri",
    description:
      "Riller, tør svær, liggende steg, 200 °C start og 160 °C finish. Skæv svær rettet.",
    recipes: [
      "airfryer/flaeskesteg",
      "ovn/gammeldags-flaeskesteg-sproede-svaer",
      "airfryer/flaeskestegssandwich",
      "sous-vide/flaeskesteg-sous-vide",
      "grill/flaeskesteg-rotisseri",
      "airfryer/flaeskesvaer-sennepsstoev",
    ],
  },
  {
    slug: "pizzadej-fejlfinding",
    title: "Fejlfinding på pizzadej: hvorfor hæver, klistrer eller trækker den sig sammen?",
    description:
      "Pizzadej som elastik, lim eller død klump. Hydrering, gluten, koldhæv og temperatur.",
    recipes: [
      "roeremaskine/neapolitansk-pizzadej-roeremaskine",
      "roeremaskine/koldhaevet-pizzadej-roeremaskine",
      "roeremaskine/hurtig-pizzadej-roeremaskine",
      "grill/pizzadej-grill",
      "pizzaovn/neapolitansk-pizza-pizzaovn",
      "pizzaovn/pizza-margherita-pizzaovn",
      "roeremaskine/detroit-pizzadej-roeremaskine",
    ],
  },
  {
    slug: "holdbarhed-i-koeleskab",
    title: "Hvor længe kan mad holde sig i køleskabet? Oversigt og sandheden om datoen",
    description:
      "Tabel over hverdagsmad: kylling, pasta, ost og rester. Sidste anvendelse versus bedst før.",
    recipes: [
      "airfryer/haardkogte-aeg-meal-prep",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "pande/frittata",
      "grill/pulled-pork",
      "dips/hummus",
    ],
  },
  {
    slug: "genopvarmning-af-mad",
    title: "Genopvarmning af mad: sådan undgår du tørt kød og bløde pommes frites",
    description:
      "Pizza, flæskesteg, pomfritter og pulled pork i airfryer, ovn og pande med damp.",
    recipes: [
      "airfryer/frosne-pomfritter",
      "airfryer/flaeskesteg",
      "grill/pulled-pork",
      "pizzaovn/pizza-margherita-pizzaovn",
      "pande/biksemad-spejlaeg",
      "gryde/bolognese",
    ],
  },
  {
    slug: "koed-svind-og-portioner",
    title: "Hvor meget svinder kød ved tilberedning? Beregn til gæster",
    description:
      "Råvægt versus tilberedt vægt for pulled pork, culotte, kamsteg og hakket.",
    recipes: [
      "grill/pulled-pork",
      "grill/culottesteg-paa-grill",
      "sous-vide/pulled-pork-sous-vide",
      "grill/tomahawk-steak",
      "airfryer/rosa-culottesteg",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "roget-smag-uden-rygeovn",
    title: "Den nemme guide til røget smag uden en rygeovn",
    description:
      "Røgsalt, røget paprika og liquid smoke. Dosering så det ikke smager af askebæger.",
    recipes: [
      "ovn/ovn-roget-pulled-chicken",
      "roeg/roget-salt",
      "dips/bbq-sauce",
      "grill/pulled-pork",
      "airfryer/beef-jerky",
      "dips/hovmestersauce",
    ],
  },
  {
    slug: "rensning-af-svampe",
    title: "Rensning af svampe: må man vaske svampe med vand?",
    description:
      "Hvornår du børster, hvornår en hurtig skylning er i orden, og hvordan du tørrer dem.",
    recipes: [
      "grill/grillede-portobellosvampe-hvidloegssmoer",
      "stobejern/cremet-svampetoast",
      "stobejern/svampe-risotto",
      "airfryer/svampe-bites-timian",
      "dehydrator/toerrede-svampe-dehydrator",
      "pizzaovn/pizza-bianca-troffel-svampe-pizzaovn",
    ],
  },
  {
    slug: "traekul-vs-briketter",
    title: "Trækul vs. briketter: hvad skal du vælge til din grill?",
    description:
      "Brændtid, high heat versus low & slow, aske og smag — lump eller briketter.",
    recipes: [
      "grill/pulled-pork",
      "grill/tomahawk-steak",
      "grill/hjemmelavet-burger",
      "grill/hel-kylling-gasgrill-tid",
      "grill/culottesteg-paa-grill",
      "grill/kernetemperatur-grill",
    ],
  },
  {
    slug: "kan-man-fryse",
    title: "Kan man fryse …? Den ultimative liste over madvarer du er i tvivl om",
    description:
      "Alfabetisk ja/nej: hytteost, fløde, æg, ost og resten — plus hvad der sker med konsistensen.",
    recipes: [
      "stobejern/grydebroed-hytteost",
      "gryde/bolognese",
      "grill/pulled-pork",
      "ovn/grove-proteinboller-kerner-hytteost",
      "airfryer/frosne-rundstykker",
      "pande/gyoza-fra-frost-pande",
    ],
  },
  {
    slug: "ris-fejlfinding",
    title: "Hvorfor klistrer mine ris? Fejlfinding på løse, kogte ris",
    description:
      "Stivelse, skylning, vandforhold og hvile under låg — så risene ikke bliver grød.",
    recipes: [
      "pande/stegte-ris-aeg-rejer",
      "trykkoger/ris-trykkoger",
      "plancha/lynstegte-ris-og-nudler",
      "gryde/kylling-i-karry",
      "trykkoger/risengrod-trykkoger",
      "stobejern/svampe-risotto",
    ],
  },
  {
    slug: "red-maden",
    title: "Red maden: for salt, for stærk eller for syrlig",
    description:
      "Akut redning med fortynding, fedt, sukker og syre. Kartoffel-tricket uden myter.",
    recipes: [
      "gryde/kylling-i-karry",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "dips/bbq-sauce",
      "stobejern/okseskank-roedvin",
      "dips/hovmestersauce",
    ],
  },
  {
    slug: "natron-og-bagepulver",
    title: "Forskellen på natron og bagepulver (og hvad du kan erstatte med)",
    description:
      "Natron kræver syre. Omregning når du mangler den ene pose midt i dejen.",
    recipes: [
      "airfryer/guleroeds-muffins",
      "ovn/flettet-hytteostbroed-pepperoni",
      "plancha/plancha-flatbread-zaatar",
      "roeremaskine/saltkringler-roeremaskine",
      "ovn/grove-proteinboller-kerner-hytteost",
      "stobejern/klassisk-grydebroed",
    ],
  },
  {
    slug: "stoebjern-seasoning",
    title: "Krydring og pleje af støbejern: rusten eller brændt pande",
    description:
      "Seasoning i ovnen, rust-redning, og hvorfor en dråbe sæbe ikke ødelægger panden.",
    recipes: [
      "stobejern/cast-iron-ribeye",
      "stobejern/smash-burgers-stobejern",
      "stobejern/stegte-flaeskesider",
      "stobejern/klassisk-grydebroed",
      "pande/pandeskaft",
      "stobejern/confiterede-andelaar",
    ],
  },
  {
    slug: "hakket-oksekoed-farve",
    title: "Mørkt kød eller gråt kød? Er hakket oksekød for gammelt?",
    description:
      "Myoglobin og iltning versus råd. Brun midte i bakken er ofte luft, ikke lig.",
    recipes: [
      "pande/hakkeboef-loeg-spejlaeg",
      "grill/hjemmelavet-burger",
      "plancha/smash-burger-paa-plancha",
      "pande/hakket-oksekoed-spidskaal",
      "gryde/bolognese",
      "gryde/chili-con-carne",
    ],
  },
  {
    slug: "omregning-gram-ske-dl",
    title: "Hvor meget vejer en …? Omregner fra gram til spiseskeer og dl",
    description:
      "Smør, mel, æg og salt i skeer og dl når vægten ligger i skuffen.",
    recipes: [
      "airfryer/guleroeds-muffins",
      "stobejern/klassisk-grydebroed",
      "roeremaskine/neapolitansk-pizzadej-roeremaskine",
      "ovn/koldhaevede-morgenboller-oelandshvede",
      "dips/aioli",
      "gryde/bolognese",
    ],
  },
  {
    slug: "airfryer-ovn-omregning",
    title: "Airfryer vs. ovn: sådan omregner du tid og temperatur",
    description:
      "Minus 20 °C og 20 % tid — plus tabel og de tilfælde formlen ikke dækker.",
    recipes: [
      "airfryer/hjemmelavede-kyllingenuggets",
      "airfryer/hel-kylling",
      "airfryer/frosne-pomfritter",
      "airfryer/guleroeds-muffins",
      "ovn/koldhaevede-morgenboller-oelandshvede",
      "airfryer/flaeskesteg",
    ],
  },
  {
    slug: "stegning-olier-roegpunkt",
    title: "Hvilken olie skal jeg stege i? Røgpunkter for begyndere",
    description:
      "Olivenolie, smør, raps og sear. Tabel over røgpunkter til pande og wok.",
    recipes: [
      "stobejern/cast-iron-ribeye",
      "pande/pandeskaft",
      "plancha/smash-burger-paa-plancha",
      "sous-vide/ribeye-sous-vide",
      "grill/tomahawk-steak",
      "pande/kyllingebryst-pande",
    ],
  },
  {
    slug: "sproede-pomfritter",
    title: "Hvorfor bliver mine pomfritter bløde? Hemmeligheden bag sprøde frites",
    description:
      "Udvask stivelse, tør helt, to omgange i ovn, airfryer eller friture.",
    recipes: [
      "airfryer/pommes-frites-bagekartofler",
      "airfryer/grovfritter-udbloedning",
      "airfryer/frosne-pomfritter",
      "fermentering/fermenterede-pommes-frites",
      "airfryer/chili-cheese-pommes",
      "airfryer/smashed-potato-salad",
    ],
  },
  {
    slug: "andesteg-komplet-guide",
    title: "Andesteg komplet — sprødt skind, temperatur og metode",
    description:
      "Tørring, scoring, kernetemperatur og sammenligning af grill, ovn, airfryer, trykkoger og sous vide.",
    recipes: [
      "grill/andesteg-paa-grill",
      "grill/and-rotisseri",
      "ovn/sproedstegt-andesteg-aebler-svesker",
      "airfryer/andesteg-airfryer",
      "trykkoger/andesteg-trykkoger",
      "sous-vide/hel-and-sous-vide",
      "stobejern/andesteg-stobejern",
      "airfryer/andelaar-airfryer",
      "plancha/andesteg-plancha",
      "pande/brunede-kartofler-and",
      "gryde/aeble-kompot-and",
      "sylte/klassisk-roedkaal-andefedt",
      "dips/andesky",
    ],
  },
  {
    slug: "mortensaften-tilbehoer",
    title: "Mortensaften-tilbehør — rødkål, kartofler og sauce til and",
    description:
      "Tilbehør til andesteg — rødkål, brunede kartofler, æblekompot, rødbeder og andesky.",
    recipes: [
      "sylte/klassisk-roedkaal-andefedt",
      "trykkoger/roedkaal-trykkoger",
      "pande/brunede-kartofler-and",
      "gryde/aeble-kompot-and",
      "gryde/rodbeder-til-and",
      "gryde/kartoffelmos-andefedt",
      "dips/andesky",
      "grill/grillede-aebler-svesker",
    ],
  },
  {
    slug: "julemenu-sammensaetning",
    title: "Julemenu — sammensæt julefrokost og juleaften",
    description:
      "Pålæg, flæskesteg, and, risengrod og desserter til det danske julebord.",
    recipes: [
      "palaeg/julefrokost-tallerken",
      "palaeg/julesylte",
      "palaeg/leverpostej",
      "ovn/gammeldags-flaeskesteg-sproede-svaer",
      "airfryer/flaeskesteg",
      "trykkoger/flaeskesteg-trykkoger",
      "grill/julegaas-rotisseri",
      "gryde/klassisk-risengrod",
      "airfryer/risengrod-airfryer",
      "ovn/klejner-ovn",
      "airfryer/aebleskiver-airfryer",
      "gryde/aebleflaesk-jul",
    ],
  },
  {
    slug: "danske-klassikere-guide",
    title: "Danske klassikere — metoder, retter og hvad du laver hvor",
    description:
      "Boller i karry, stegt flæsk, forloren hare, rødgrød og 15+ retter på tværs af airfryer, grill, ovn, gryde og trykkoger.",
    recipes: [
      "gryde/boller-i-karry",
      "trykkoger/boller-i-karry-trykkoger",
      "airfryer/stegt-flaesk",
      "grill/stegt-flaesk-grill",
      "ovn/stegt-flaesk-ovn",
      "pande/stegt-flaesk-pande",
      "gryde/klassisk-rodgroed",
      "ovn/klassisk-aeblekage",
      "gryde/koldskal",
      "gryde/forloren-hare-gryde",
      "stobejern/forloren-hare-stobejern",
      "pande/stjerneskud",
      "airfryer/stjerneskud-airfryer",
      "gryde/hjerter-i-floedesovs",
      "gryde/skipperlabskovs",
      "palaeg/leverpostej",
      "ovn/hjemmelavet-leverpostej",
    ],
  },
  {
    slug: "fryseguide-madpakke",
    title: "Den store fryseguide til børnenes madpakke",
    description:
      "Hvad der kan fryses til madpakken, og hvordan det tør op uden at blive svampet.",
    recipes: [
      "roeremaskine/pizzasnegle-roeremaskine",
      "pizzaovn/protein-pizzasnegle-hytteost-pizzaovn",
      "airfryer/poelsehorn",
      "ovn/protein-poelsehorn-hytteost",
      "ovn/hytteost-madboller-havregryn",
      "ovn/grove-proteinboller-kerner-hytteost",
      "airfryer/frosne-rundstykker",
      "airfryer/mini-pizzasnegle",
    ],
  },
  {
    slug: "skjul-groentsager-kraesne-boern",
    title: "Mad til kræsne børn: Skjul grøntsagerne",
    description:
      "Grøntsager der kan blendes i kødsovs, pandekager, tomatsauce og deller.",
    recipes: [
      "gryde/bolognese",
      "pande/frikadeller-pande",
      "airfryer/frikadeller",
      "pande/koedboller-tomatsauce",
      "pande/amerikanske-pandekager",
      "airfryer/guleroeds-muffins",
      "pizzaovn/protein-pizzabund-hytteost-havre-pizzaovn",
      "pande/hakket-oksekoed-spidskaal",
    ],
  },
  {
    slug: "airfryer-boernemad-15-minutter",
    title: "Airfryer-børnemad på under 15 minutter",
    description:
      "Nuggets, fiskefileter, pølsehorn og mini-pizza efter institution.",
    recipes: [
      "airfryer/hjemmelavede-kyllingenuggets",
      "airfryer/kyllingenuggets",
      "airfryer/fiskefileter-panko",
      "airfryer/poelsehorn",
      "airfryer/mini-pizza",
      "airfryer/mini-pizzasnegle",
      "airfryer/hotdogs-poelser",
      "airfryer/frosne-pomfritter",
    ],
  },
  {
    slug: "proteiner-uden-koed-boern",
    title: "Hurtige proteiner til børn, der ikke gider kød",
    description:
      "Hytteost i vafler og deller, æg og hummus når kylling er et nej.",
    recipes: [
      "pande/salte-hytteostvafler",
      "pande/amerikanske-pandekager",
      "pande/frittata",
      "airfryer/haardkogte-aeg-meal-prep",
      "ovn/hytteost-madboller-havregryn",
      "ovn/grove-proteinboller-kerner-hytteost",
      "pizzaovn/kyllingefrikadeller-hytteost-fad-pizzaovn",
      "dips/hummus",
      "airfryer/hytteost-muffins-kalkunbacon",
      "pande/english-muffins-hytteost",
    ],
  },
  {
    slug: "fingermad-snacks-til-turen",
    title: "Fingermad og snacks til turen",
    description:
      "Havrekugler, bananmuffins og majs der ikke klistrer i bilen.",
    recipes: [
      "ovn/hytteost-madboller-havregryn",
      "airfryer/guleroeds-muffins",
      "pizzaovn/havre-bananbroed-eftervarme-pizzaovn",
      "dips/hummus",
      "airfryer/pitabroed",
      "ovn/grove-proteinboller-kerner-hytteost",
      "pizzaovn/knaekbroed-hytteost-froe-pizzaovn",
      "airfryer/ostestaenger-hytteost-chili",
    ],
  },
  {
    slug: "bloed-mad-taender-boejle",
    title: "Blød mad til ømme gummer",
    description:
      "Kolde smoothies, cremede supper og grød når tænder eller bøjle strammer.",
    recipes: [
      "trykkoger/tomatsuppe-trykkoger",
      "trykkoger/risengrod-trykkoger",
      "trykkoger/aeblemos-trykkoger",
      "pande/amerikanske-pandekager",
      "pande/frittata",
      "pande/salte-hytteostvafler",
      "gryde/boller-i-karry",
      "stobejern/grydebroed-hytteost",
    ],
  },
  {
    slug: "boerenefoedselsdag-paa-budget",
    title: "Børnefødselsdag på budget",
    description:
      "Mini-pizza, pølsehunde og pastabar til mange børn uden dyrt setup.",
    recipes: [
      "airfryer/mini-pizza",
      "airfryer/poelsehorn",
      "airfryer/hotdogs-poelser",
      "gryde/one-pot-pasta",
      "pande/tacos-krydret-hakkekoed",
      "roeremaskine/pizzasnegle-roeremaskine",
      "pande/amerikanske-pandekager",
      "airfryer/hjemmelavede-kyllingenuggets",
    ],
  },
  {
    slug: "sund-fredagsslik",
    title: "Sund fredagsslik",
    description:
      "Banan-pops, æble-chips og vandmelon-pizza — slik-følelse med frugt og kakao.",
    recipes: [
      "airfryer/guleroeds-muffins",
      "pizzaovn/havre-bananbroed-eftervarme-pizzaovn",
      "pizzaovn/bagt-hytteost-dip-chili-pizzaovn",
      "pande/amerikanske-pandekager",
      "pande/franske-toast",
      "trykkoger/aeblemos-trykkoger",
      "ovn/hytteost-madboller-havregryn",
    ],
  },
  {
    slug: "foerste-rigtige-mad-baby",
    title: "Den første rigtige mad: Fra babymos til familiens mad",
    description:
      "Stykker, honning, salt og familiens gryde omkring 8–10 måneder.",
    recipes: [
      "pande/amerikanske-pandekager",
      "pande/frittata",
      "gryde/bolognese",
      "pande/frikadeller-pande",
      "trykkoger/aeblemos-trykkoger",
      "trykkoger/risengrod-trykkoger",
      "pande/salte-hytteostvafler",
    ],
  },
  {
    slug: "byg-selv-retter-middagsbordet",
    title: "Nemme byg-selv-retter ved middagsbordet",
    description:
      "Tacos, pita, fladbrød og mini-pizza så børnene selv styrer tallerkenen.",
    recipes: [
      "pande/tacos-krydret-hakkekoed",
      "airfryer/tacoskaller-airfryer",
      "airfryer/mini-pizza",
      "airfryer/pitabroed",
      "ovn/viral-hytteost-fladbroed",
      "pande/pande-fladbroed-hytteost",
      "grill/hjemmelavet-burger",
      "pande/amerikanske-pandekager",
    ],
  },
];

export function getGuidesMentioningRecipe(category: string, slug: string) {
  const key = `${category}/${slug}`;
  return GUIDE_LINKS.filter((guide) => guide.recipes.includes(key));
}
