/** Client-safe guide-meta (ingen fs). Hold synk med content/guides/*.mdx. */

export const GUIDE_NAV = [
  { slug: "airfryer-for-begyndere", name: "Airfryer for begyndere" },
  { slug: "kernetemperatur", name: "Kernetemperatur" },
  { slug: "culottesteg", name: "Culottesteg" },
  { slug: "hjemmelavet-pizza", name: "Hjemmelavet pizza" },
  { slug: "pulled-pork", name: "Pulled pork" },
  { slug: "fermentering-for-begyndere", name: "Fermentering" },
  { slug: "syltning", name: "Syltning" },
  { slug: "roegning-hjemme", name: "Røgning hjemme" },
  { slug: "grydebroed-og-focaccia", name: "Grydebrød og focaccia" },
  { slug: "smash-burger", name: "Smash burger" },
  { slug: "saltguide", name: "Saltguide" },
  { slug: "dehydrering-for-noerder", name: "Dehydrering" },
  { slug: "sous-vide-grill", name: "Sous vide + sear" },
  { slug: "baalmad", name: "Bålmad" },
  { slug: "stegeoverflader", name: "Stegeoverflader" },
  { slug: "trykkoger-og-slowcooker", name: "Trykkoger" },
  { slug: "avanceret-fermentering", name: "Koji og miso" },
  { slug: "saucer-fond-reduktion", name: "Fond og saucer" },
  { slug: "konfittering", name: "Konfittering" },
  { slug: "grill-for-begyndere", name: "Grill for begyndere" },
  { slug: "grillrist-og-pander-pleje", name: "Grillrist og pander" },
  { slug: "meal-prep", name: "Meal prep" },
  { slug: "mad-paa-budget", name: "Mad på budget" },
  { slug: "frysning-og-optoening", name: "Frysning og optøning" },
  { slug: "groentsager-paa-grillen", name: "Grøntsager på grillen" },
  { slug: "boerenevenlig-madlavning", name: "Børnevenlig madlavning" },
  { slug: "marinader-og-rubs", name: "Marinader og rubs" },
  { slug: "bageskole-gaer-og-haevning", name: "Bageskole" },
  { slug: "sikker-madlavning", name: "Sikker madlavning" },
] as const;

export type GuideNavSlug = (typeof GUIDE_NAV)[number]["slug"];

export const GUIDE_LINKS: {
  slug: GuideNavSlug;
  title: string;
  description: string;
  recipes: string[];
}[] = [
  {
    slug: "airfryer-for-begyndere",
    title: "Airfryer for begyndere — sprød mad uden gætteri",
    description:
      "Komplet guide til airfryer: temperatur, tid, forvarmning, olie og de fejl der gør maden blød.",
    recipes: [
      "airfryer/pommes-frites-bagekartofler",
      "airfryer/frosne-pomfritter",
      "airfryer/crispy-chicken-tenders",
      "airfryer/hjemmelavede-kyllingenuggets",
      "airfryer/flaeskesvaer-sennepsstoev",
      "airfryer/bacon",
      "airfryer/hel-kylling",
      "airfryer/fiskefileter-panko",
      "airfryer/smashed-potato-salad",
      "airfryer/haardkogte-aeg-meal-prep",
      "airfryer/frosne-rundstykker",
      "airfryer/spidskaal",
    ],
  },
  {
    slug: "kernetemperatur",
    title: "Kernetemperatur — komplet tabel til grill, pande, ovn og sous vide",
    description:
      "Kernetemperatur for okse, svin, lam, kylling og fisk. Træk-temperatur, carryover og probe-placering.",
    recipes: [
      "grill/kernetemperatur-grill",
      "grill/tomahawk-steak",
      "grill/culottesteg-paa-grill",
      "grill/oksemoerbrad-paa-grill",
      "sous-vide/ribeye-sous-vide",
      "sous-vide/culottesteg-sous-vide",
      "sous-vide/hel-kylling-sous-vide",
      "grill/hel-kylling-gasgrill-tid",
      "grill/pulled-pork",
      "roeg/smoked-pulled-pork",
      "sous-vide/pulled-pork-sous-vide",
      "sous-vide/laksefilet-sous-vide",
      "grill/grillet-lakseside-citron",
    ],
  },
  {
    slug: "culottesteg",
    title: "Culottesteg — fra rå til rosa på grill, ovn, airfryer og sous vide",
    description:
      "Culottesteg komplet: udskæring, fedtkappe, kernetemperatur, reverse sear og hvile.",
    recipes: [
      "grill/culottesteg-paa-grill",
      "grill/culottesteg-rotisseri",
      "grill/grillet-kalveculotte-urtemarinade",
      "sous-vide/culottesteg-sous-vide",
      "airfryer/rosa-culottesteg",
      "grill/klassisk-kartoffelsalat",
      "grill/kartoffelsalat-radiser",
      "dips/chimichurri",
      "dips/mormordressing",
      "grill/groentsager-paa-grill",
    ],
  },
  {
    slug: "hjemmelavet-pizza",
    title: "Hjemmelavet pizza — dej, varme og ovn",
    description:
      "Pizzadej, koldhæv, neapolitansk varme og fejl som våd midte.",
    recipes: [
      "roeremaskine/neapolitansk-pizzadej-roeremaskine",
      "roeremaskine/koldhaevet-pizzadej-roeremaskine",
      "roeremaskine/hurtig-pizzadej-roeremaskine",
      "grill/pizzadej-grill",
      "pizzaovn/neapolitansk-pizza-pizzaovn",
      "pizzaovn/pizza-margherita-pizzaovn",
      "pizzaovn/detroit-style-pizza-pizzaovn",
      "pizzaovn/calzone-skinke-ricotta-pizzaovn",
      "pizzaovn/panuozzo-pizza-sandwich-pizzaovn",
      "pizzaovn/focaccia-rosmarin-cherrytomater-pizzaovn",
      "grill/grillet-focaccia-pizzasten",
      "stobejern/overnight-sourdough-cast-iron-pizza",
      "roeremaskine/detroit-pizzadej-roeremaskine",
    ],
  },
  {
    slug: "pulled-pork",
    title: "Pulled pork — nakkefilet til trækbar",
    description:
      "Pulled pork komplet: nakkefilet, rub, stall, probe tender og 93–95 °C.",
    recipes: [
      "grill/pulled-pork",
      "grill/asiatisk-sticky-pulled-pork",
      "roeg/smoked-pulled-pork",
      "stobejern/pulled-pork-dutch-oven",
      "sous-vide/pulled-pork-sous-vide",
      "trykkoger/pulled-pork-trykkoger",
      "roeg/smoked-pork-belly-sliders",
      "dips/bbq-sauce",
      "grill/klassisk-kartoffelsalat",
      "sylte/syltede-roedloeg-10-minutter",
      "roeremaskine/brioche-burgerboller-roeremaskine",
    ],
  },
  {
    slug: "fermentering-for-begyndere",
    title: "Fermentering for begyndere — salt, lage og mælkesyre",
    description:
      "Fermentering hjemme: 2 % salt, lage, kahm versus skimmel og temperatur.",
    recipes: [
      "fermentering/klassisk-sauerkraut",
      "fermentering/autentisk-koreansk-kimchi",
      "fermentering/maelkesyregaerde-agurker",
      "fermentering/fermenterede-roedloeg",
      "fermentering/nordisk-gravad-laks",
      "fermentering/saltkonserverede-citroner",
      "fermentering/fermenteret-chili-hot-sauce",
      "fermentering/hjemmelavet-bacon-saltning",
      "fermentering/fermenterede-guleroedsstave-ingefaer",
      "fermentering/curtido",
    ],
  },
  {
    slug: "syltning",
    title: "Syltning — lage, forhold og glas der holder",
    description:
      "Syltning med eddike: forhold, hurtigsylt versus kogning, agurker, rødløg og asier.",
    recipes: [
      "sylte/syltede-agurker",
      "sylte/hurtigsyltede-agurker-10-minutter",
      "sylte/gammeldags-agurkesalat-peberkorn",
      "sylte/asier",
      "sylte/syltede-roedloeg",
      "sylte/syltede-roedloeg-10-minutter",
      "sylte/syltede-jalapenos",
      "sylte/cowboy-candy",
      "sylte/syltede-roedbeder",
      "sylte/syltede-radiser",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "roegning-hjemme",
    title: "Røgning hjemme — koldrøg versus varmrøg, den komplette guide",
    description:
      "Koldrøg vs. varmrøg, træsorter, røg-generatorer, pellicle og sikkerhed.",
    recipes: [
      "roeg/koldroget-laks",
      "grill/koldroget-laks-paa-grill",
      "roeg/hjemmelavet-koldroget-bacon",
      "roeg/varmroget-lakseside",
      "roeg/varmroget-sild",
      "roeg/smoked-beef-brisket",
      "roeg/smoked-pork-ribs",
      "roeg/smoked-pulled-pork",
      "roeg/roget-salt",
      "roeg/smoked-cream-cheese",
      "fermentering/hjemmelavet-bacon-saltning",
    ],
  },
  {
    slug: "grydebroed-og-focaccia",
    title: "Grydebrød og focaccia — skorpe i støbejern",
    description:
      "Grydebrød og focaccia: hydrering, salt i dejen, damp under låg, surdej versus gær.",
    recipes: [
      "stobejern/klassisk-grydebroed",
      "stobejern/grydebroed-oel-kerner",
      "stobejern/grydebroed-hytteost",
      "stobejern/rugbroeds-grydebroed",
      "stobejern/hvidloegs-krydderurte-focaccia",
      "roeremaskine/focaccia-havsalt-roeremaskine",
      "roeremaskine/grydebroad-roeremaskine",
      "pizzaovn/focaccia-rosmarin-cherrytomater-pizzaovn",
      "pizzaovn/roedbede-focaccia-timian-pizzaovn",
      "grill/grillet-focaccia-pizzasten",
      "roeremaskine/ciabatta-roeremaskine",
      "roeremaskine/naanbroed-roeremaskine",
    ],
  },
  {
    slug: "smash-burger",
    title: "Smash burger — plancha, grill og sauce",
    description:
      "Smash burger hjemme: fedtprocent, smash-teknik, ost, bolle og pickles.",
    recipes: [
      "plancha/smash-burger-paa-plancha",
      "plancha/smash-burger-sliders-paa-plancha",
      "stobejern/smash-burgers-stobejern",
      "pizzaovn/smash-burgers-pizzaovn",
      "grill/hjemmelavet-burger",
      "roeremaskine/brioche-burgerboller-roeremaskine",
      "dips/burgersauce",
      "dips/aioli",
      "sylte/syltede-roedloeg-10-minutter",
      "sylte/hurtigsyltede-agurker-10-minutter",
      "airfryer/frosne-pomfritter",
      "airfryer/bacon",
    ],
  },
  {
    slug: "saltguide",
    title: "Den ultimative saltguide — typer, procenter og funktion",
    description:
      "Flagesalt, dæmningssalt, nitritsalt og koldrøget salt. Tørsaltning versus saltlage.",
    recipes: [
      "fermentering/gourmetsaltning-oksekoed",
      "fermentering/hjemmelavet-bacon-saltning",
      "fermentering/klassisk-sauerkraut",
      "fermentering/spraengt-svinemoerbrad",
      "fermentering/saltede-aeggeblommer",
      "fermentering/saltede-kapers",
      "fermentering/nordisk-gravad-laks",
      "roeg/roget-salt",
      "dehydrator/urtesalt-dehydrator",
      "dehydrator/ramslogssalt-dehydrator",
      "ovn/braendt-hvidloegssalt",
    ],
  },
  {
    slug: "dehydrering-for-noerder",
    title: "Dehydrering for nørder — jerky, støv og umami-bomber",
    description:
      "Temperaturer og tider til jerky, svampestøv, urtesalt og kapers.",
    recipes: [
      "dehydrator/beef-jerky-dehydrator",
      "dehydrator/bacon-jerky-dehydrator",
      "dehydrator/salmon-jerky-dehydrator",
      "dehydrator/toerrede-svampe-dehydrator",
      "dehydrator/svampesalt-dehydrator",
      "dehydrator/tomatpulver-dehydrator",
      "dehydrator/loegpulver-dehydrator",
      "dehydrator/urtesalt-dehydrator",
      "dehydrator/semidried-tomater-dehydrator",
      "fermentering/saltede-kapers",
      "dehydrator/flaeskesvaer-dehydrator",
    ],
  },
  {
    slug: "sous-vide-grill",
    title: "Sous vide + grill og pande — reverse sear der rammer",
    description:
      "Tider og temperaturer til bad, genopvarmning og skorpe på plancha og støbejern.",
    recipes: [
      "sous-vide/ribeye-sous-vide",
      "sous-vide/entrecote-sous-vide",
      "sous-vide/tomahawk-steak-sous-vide",
      "sous-vide/culottesteg-sous-vide",
      "sous-vide/flanksteak-sous-vide",
      "sous-vide/laksefilet-sous-vide",
      "sous-vide/pulled-pork-sous-vide",
      "plancha/tomahawk-steak-board-sauce-plancha",
      "stobejern/cast-iron-ribeye",
      "fermentering/gourmetsaltning-oksekoed",
    ],
  },
  {
    slug: "baalmad",
    title: "Bålmad — glødebed, trefod og Dutch Oven i ilden",
    description:
      "Styring af varme med brænde, glødebed, trefod og Dutch Oven i gløderne.",
    recipes: [
      "baalmad/ribeye-med-urtesmoer",
      "baalmad/tomahawk-steak-paa-aaben-ild",
      "baalmad/gullasch-i-dutch-oven",
      "baalmad/ossobuco-i-gloedene",
      "baalmad/gloedestegte-porrer",
      "baalmad/skipperlabskovs-over-baal",
      "baalmad/hvidloegs-focaccia-i-gryde",
      "baalmad/stobejerns-focaccia-med-rosmarin",
      "baalmad/plankelaks-med-enebaer",
      "baalmad/flanksteak-med-chimichurri",
    ],
  },
  {
    slug: "stegeoverflader",
    title: "Stegeoverflader — støbejern, plancha og rustfrit stål",
    description:
      "Hvornår du bruger hvad, seasoning af støbejern og Maillard uden at brænde på.",
    recipes: [
      "stobejern/cast-iron-ribeye",
      "stobejern/smash-burgers-stobejern",
      "plancha/smash-burger-paa-plancha",
      "plancha/tomahawk-steak-board-sauce-plancha",
      "plancha/engelsk-bof-paa-plancha",
      "stobejern/klassisk-grydebroed",
      "stobejern/stegte-flaeskesider",
      "pande/pandeskaft",
      "sous-vide/ribeye-sous-vide",
    ],
  },
  {
    slug: "trykkoger-og-slowcooker",
    title: "Trykkoger og slowcooker — kollagen, tid og væske",
    description:
      "Hvordan tryk nedbryder kollagen i skanker og oksehaler. Tid og væskeforhold.",
    recipes: [
      "trykkoger/osso-buco-trykkoger",
      "trykkoger/svinekaeber-trykkoger",
      "trykkoger/pulled-pork-trykkoger",
      "trykkoger/fond-trykkoger",
      "trykkoger/oksespidsbryst-trykkoger",
      "trykkoger/gullasch-trykkoger",
      "stobejern/okseskank-roedvin",
      "stobejern/oksehale-moerkt-oel",
      "stobejern/pulled-pork-dutch-oven",
      "sous-vide/osso-buco-sous-vide",
    ],
  },
  {
    slug: "avanceret-fermentering",
    title: "Avanceret fermentering — koji, miso og eddiker fra bunden",
    description:
      "Aspergillus oryzae, shio koji, miso, garum og frugteddiker.",
    recipes: [
      "fermentering/klassisk-shio-koji",
      "fermentering/hjemmelavet-shiro-miso",
      "fermentering/koji-modnet-steak",
      "fermentering/gochujang-fra-bunden",
      "fermentering/hjemmelavet-shoyu-svampe",
      "fermentering/lyn-garum-oksekoed",
      "fermentering/klassisk-romersk-fiskegarum",
      "fermentering/fermenteret-aebleeddike",
      "fermentering/hjemmelavet-eddike-vinrester",
      "fermentering/kombucha-eddike",
    ],
  },
  {
    slug: "saucer-fond-reduktion",
    title: "Saucer på fond og reduktion — gastrique, montering og glace",
    description:
      "Reduktion, gastrique, koldt smør og glinsende glace.",
    recipes: [
      "trykkoger/fond-trykkoger",
      "ovn/bagt-marvben-persillesalat",
      "dips/whiskeysauce",
      "dips/bbq-sauce",
      "dips/hovmestersauce",
      "stobejern/okseskank-roedvin",
      "stobejern/oksehale-moerkt-oel",
      "stobejern/ossobuco-alla-milanese",
      "plancha/tomahawk-steak-board-sauce-plancha",
      "pande/torskefilet-smoersauce",
    ],
  },
  {
    slug: "konfittering",
    title: "Konfittering — mørhed og hold i rent fedt",
    description:
      "Temperaturstyring omkring 85–90 °C i andefedt, svinefedt eller olivenolie.",
    recipes: [
      "stobejern/confiterede-andelaar",
      "sous-vide/andelaar-sous-vide",
      "stobejern/confiterede-hvidloeg-andefedt",
      "sous-vide/hvidloegsconfit-sous-vide",
      "sylte/hvidloegsconfit",
      "ovn/langtidsbagte-confiterede-cherrytomater",
      "fermentering/saltet-toerret-andebryst",
      "sous-vide/hel-and-sous-vide",
    ],
  },
  {
    slug: "grill-for-begyndere",
    title: "Den store grill-guide til begyndere — gas vs. kul",
    description:
      "Gas versus kul, tænding, zoner, direkte og indirekte varme.",
    recipes: [
      "grill/hel-kylling-gasgrill-tid",
      "grill/grillkylling",
      "grill/kernetemperatur-grill",
      "grill/tomahawk-steak",
      "grill/culottesteg-paa-grill",
      "grill/svinemoerbrad",
      "grill/groentsager-paa-grill",
      "grill/majskolber",
      "grill/pulled-pork",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "grillrist-og-pander-pleje",
    title: "Klargøring og pleje af grillriste og pander",
    description:
      "Afbrænding, rust, seasoning og kød der ikke hænger i.",
    recipes: [
      "stobejern/cast-iron-ribeye",
      "stobejern/smash-burgers-stobejern",
      "stobejern/stegte-flaeskesider",
      "plancha/smash-burger-paa-plancha",
      "pande/pandeskaft",
      "grill/culottesteg-paa-grill",
      "grill/tomahawk-steak",
      "grill/hjemmelavet-burger",
    ],
  },
  {
    slug: "meal-prep",
    title: "Måltidsforberedelse (meal prep) til en travl uge",
    description:
      "Planlæg, kog, pak og opbevar så hverdagen er 10 minutter.",
    recipes: [
      "airfryer/haardkogte-aeg-meal-prep",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "gryde/kylling-i-karry",
      "gryde/one-pot-pasta",
      "pande/hakket-oksekoed-spidskaal",
      "pande/frittata",
      "grill/pulled-pork",
      "dips/hummus",
      "ovn/grove-proteinboller-kerner-hytteost",
    ],
  },
  {
    slug: "mad-paa-budget",
    title: "Den nemme guide til mad på budget",
    description:
      "Madspild, sæson, billige udskæringer og gryder der mætter.",
    recipes: [
      "gryde/skipperlabskovs",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "gryde/millionboef",
      "gryde/hvidkaalssuppe-flaesk",
      "gryde/boller-i-karry",
      "pande/biksemad-spejlaeg",
      "pande/hakkeboef-loeg-spejlaeg",
      "pande/stegt-lever-bloede-loeg",
      "gryde/one-pot-poelseret",
    ],
  },
  {
    slug: "frysning-og-optoening",
    title: "Alt om frysning og optøning af mad",
    description:
      "Hvad der tåler frost, sikker tø af kød og holdbarhed ved −18 °C.",
    recipes: [
      "grill/pulled-pork",
      "gryde/bolognese",
      "gryde/chili-con-carne",
      "gryde/gullasch",
      "stobejern/klassisk-grydebroed",
      "roeremaskine/brioche-burgerboller-roeremaskine",
      "airfryer/frosne-pomfritter",
      "airfryer/frosne-rundstykker",
      "pande/gyoza-fra-frost-pande",
    ],
  },
  {
    slug: "groentsager-paa-grillen",
    title: "Grøntsager på grillen — tider og teknikker",
    description:
      "Majs, asparges, peber og spidskål uden sort skorpe og slatten midte.",
    recipes: [
      "grill/groentsager-paa-grill",
      "grill/majskolber",
      "grill/elote-majskolber",
      "grill/groenne-asparges",
      "grill/grillet-spidskaal",
      "grill/grillet-aubergine",
      "grill/grillet-squash",
      "grill/grillede-tomater",
      "grill/groentsagsspyd",
      "grill/grillede-portobellosvampe-hvidloegssmoer",
    ],
  },
  {
    slug: "boerenevenlig-madlavning",
    title: "Børnevenlig madlavning — succes med ungerne",
    description:
      "Opgaver efter alder, mindre kaos, retter der tåler små hænder.",
    recipes: [
      "pande/amerikanske-pandekager",
      "pande/frikadeller-pande",
      "gryde/boller-i-karry",
      "grill/hjemmelavet-burger",
      "gryde/one-pot-pasta",
      "pande/tacos-krydret-hakkekoed",
      "roeremaskine/pizzasnegle-roeremaskine",
      "ovn/koldhaevede-morgenboller-oelandshvede",
      "airfryer/hjemmelavede-kyllingenuggets",
      "pande/franske-toast",
    ],
  },
  {
    slug: "marinader-og-rubs",
    title: "Hjemmelavede marinader og rubs — de 5 grundsmage",
    description:
      "Olie, syre og krydderi til kylling, svin og okse. Rub til bark.",
    recipes: [
      "dips/chimichurri",
      "dips/sennep-honning-marinade-dressing",
      "dips/bbq-sauce",
      "dips/olie-eddike-dressing",
      "grill/grillet-kalveculotte-urtemarinade",
      "grill/kyllingespyd",
      "grill/svinemoerbrad",
      "grill/shish-kebab-okseklump",
      "grill/pulled-pork",
      "dips/hvidloegssmoer",
    ],
  },
  {
    slug: "bageskole-gaer-og-haevning",
    title: "Den nemme bageskole — gær, hævning og temperatur",
    description:
      "Hvorfor dejen ikke hæver, lunt versus koldt vand, boller der ikke er tætte.",
    recipes: [
      "stobejern/klassisk-grydebroed",
      "ovn/koldhaevede-morgenboller-oelandshvede",
      "roeremaskine/brioche-burgerboller-roeremaskine",
      "roeremaskine/focaccia-havsalt-roeremaskine",
      "roeremaskine/grydebroad-roeremaskine",
      "roeremaskine/hurtig-pizzadej-roeremaskine",
      "roeremaskine/koldhaevet-pizzadej-roeremaskine",
      "airfryer/frosne-rundstykker",
    ],
  },
  {
    slug: "sikker-madlavning",
    title: "Sikker madlavning — hygiejne, bakterier og holdbarhed",
    description:
      "To-timers-regel, kylling 74 °C, krydskontaminering og rester.",
    recipes: [
      "grill/hel-kylling-gasgrill-tid",
      "grill/kernetemperatur-grill",
      "airfryer/hel-kylling",
      "pande/kyllingebryst-pande",
      "pande/frikadeller-pande",
      "gryde/bolognese",
      "airfryer/haardkogte-aeg-meal-prep",
    ],
  },
];

export function getGuidesMentioningRecipe(category: string, slug: string) {
  const key = `${category}/${slug}`;
  return GUIDE_LINKS.filter((guide) => guide.recipes.includes(key));
}
